export const theme = {
  colors: {
    primary: "bg-amber-600 text-white",
    primaryHover: "hover:bg-amber-700",
    secondary: "bg-stone-700 text-white",
    secondaryHover: "hover:bg-stone-800",
    background: "bg-stone-200",
    surface: "bg-stone-50",
    surfaceDark: "bg-stone-800",
    text: "text-stone-900",
    textLight: "text-stone-100",
    textMuted: "text-stone-500",
    border: "border-stone-300",
    borderDark: "border-stone-600",
    accent: "text-amber-600",
    danger: "bg-red-600 text-white",
    dangerHover: "hover:bg-red-700",
    success: "bg-emerald-600 text-white",
  },
  rarity: {
    1: {
      label: "★1 コモン",
      stars: "★",
      bg: "bg-stone-50",
      border: "border-stone-300",
      borderSelected: "border-stone-600",
      badge: "bg-stone-200 text-stone-700 border border-stone-300",
      tag: "bg-stone-200 text-stone-700",
      text: "text-stone-800",
      starColor: "text-stone-400",
      ring: "",
      accent: "text-stone-600",
    },
    2: {
      label: "★2 レア",
      stars: "★★",
      bg: "bg-sky-50/90",
      border: "border-sky-300",
      borderSelected: "border-sky-600",
      badge: "bg-sky-100 text-sky-800 border border-sky-300",
      tag: "bg-sky-100 text-sky-800 font-bold",
      text: "text-sky-950",
      starColor: "text-sky-500",
      ring: "ring-1 ring-sky-300",
      accent: "text-sky-600",
    },
    3: {
      label: "★3 Sレア",
      stars: "★★★",
      bg: "bg-amber-50/95",
      border: "border-amber-400",
      borderSelected: "border-amber-600",
      badge: "bg-amber-100 text-amber-900 border border-amber-300 shadow-xs",
      tag: "bg-gradient-to-r from-amber-200 to-yellow-200 text-amber-900 font-bold",
      text: "text-amber-950",
      starColor: "text-amber-500",
      ring: "ring-2 ring-amber-300 shadow-sm",
      accent: "text-amber-600",
    }
  },
  workshop: {
    // 職人工房・石窯・木製梁・レンガ造りスタイル
    mainCard: "bg-[#faf5ee]/95 border-2 border-[#c29b77] shadow-md relative overflow-hidden",
    woodAccent: "border-[#8e5e3a] text-[#8e5e3a]",
    brickAccent: "border-[#b55338] text-[#b55338]",
    statCard: "bg-white/95 border-2 border-[#d6beaa] rounded-xl flex items-center p-2.5 shadow-2xs hover:border-[#b89578] transition-all",
    statIconBox: "w-9 h-9 rounded-lg flex items-center justify-center shrink-0 border mr-2.5 shadow-2xs",
    sectionDivider: "border-t-2 border-[#d9c4b1]",
    sectionHeader: "font-bold text-[#5c3e28] text-sm tracking-wider flex items-center gap-2",
    innerCard: "bg-[#fffdfa] rounded-xl border-2 border-[#dcc5b0] p-3 shadow-2xs",
  },
  studio: {
    viewportBg: "bg-stone-900 border-2 border-stone-700 shadow-inner rounded-2xl relative overflow-hidden",
    viewportLight: "bg-stone-100 border-2 border-stone-300 shadow-inner rounded-2xl relative overflow-hidden",
    stageGrid: "opacity-25 pointer-events-none absolute inset-0",
    controlPanel: "bg-[#faf6f0] border-2 border-[#cbb29a] rounded-xl p-3 shadow-sm space-y-3",
    actionButton: "border-2 border-stone-300 bg-white hover:border-amber-500 hover:bg-amber-50/80 transition-all rounded-lg p-2 text-left flex flex-col justify-between shadow-2xs cursor-pointer",
    actionButtonActive: "border-2 border-amber-600 bg-amber-100/90 text-amber-950 font-bold shadow-xs",
    tagBadge: "text-[10px] px-2 py-0.5 rounded-full font-bold shadow-2xs",
    speedBtnActive: "bg-amber-600 text-white font-bold border border-amber-700 shadow-xs",
    speedBtnInactive: "bg-stone-200 text-stone-700 hover:bg-stone-300 border border-stone-300",
    infoCard: "bg-stone-800/90 border border-stone-600 rounded-lg p-2.5 text-stone-200 text-xs shadow-inner",
  },
  spacing: {
    xs: "p-2",
    sm: "p-4",
    md: "p-6",
    lg: "p-8",
    gapSm: "gap-2",
    gapMd: "gap-4",
    gapLg: "gap-6",
  },
  radius: {
    sm: "rounded-sm",
    md: "rounded-md",
    lg: "rounded-xl",
    full: "rounded-full",
  },
  shadow: {
    sm: "shadow-sm",
    md: "shadow-md",
    lg: "shadow-xl",
  },
  zIndex: {
    base: "z-0",
    header: "z-30",
    nav: "z-40",
    modal: "z-50",
    modalOverlay: "z-[60]",
    toast: "z-[70]",
    confetti: "z-[100]",
  },
  typography: {
    h1: "text-2xl font-bold font-['DotGothic16',_sans-serif]",
    h2: "text-xl font-bold font-['DotGothic16',_sans-serif]",
    h3: "text-lg font-bold font-['DotGothic16',_sans-serif]",
    h4: "text-base font-bold font-['DotGothic16',_sans-serif]",
    body: "text-base font-['DotGothic16',_sans-serif]",
    small: "text-xs font-['DotGothic16',_sans-serif]",
  }
};
